### ISSUE TITLE
ERROR: Cannot install -r requirements.txt

### ISSUE THREAD

**Issue by WeiHao97** [zacharyhorvitz/ParaGuide#1]
The user requested fsspec==2022.5.0
    huggingface-hub 0.20.3 depends on fsspec>=2023.5.0

**Comment by WeiHao97** [comment]
ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

seems resolved by: ```pip install --ignore-installed PyYAML```

**Comment by WeiHao97** [comment]
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

seems resolved by:  ```pip install protobuf==3.20.*```

**Comment by WeiHao97** [comment]
ImportError: cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_'

seems resolved by: ```pip install 'urllib3<2'```

**Comment by WeiHao97** [comment]
AttributeError: module 'numpy' has no attribute 'typeDict'

seems resolved by:  ```pip install --upgrade h5py```

**Comment by juntaic7** [comment]
Everything seems to work simply by modifying  `fsspec==2022.5.0` to `fsspec==2023.5.0`.

**Comment by zacharyhorvitz** [comment]
> Everything seems to work simply by modifying `fsspec==2022.5.0` to `fsspec==2023.5.0`.

Thanks @juntaic7. This should be fixed as of 0d61d92
